name: Build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: microsoft/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - run: 
        dotnet new classlib -n Project
        dotnet add Project package MelonLoader --version 0.6.1
        copy *.cs Project/Class1.cs
        dotnet build Project --configuration Release
    - uses: actions/upload-artifact@v4
      with:
        name: ModFile
        path: Project/bin/Release/net6.0/*.dll
