name: Build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Force Add Source and Build
      run: |
        # ここで MelonLoader が置いてある「裏の倉庫」を強制登録する
        dotnet nuget add source https://nuget.lavalink.dev/v3/index.json -n Lavalink
        dotnet build Project.csproj --configuration Release
    - uses: actions/upload-artifact@v4
      with:
        name: ModFile
        path: bin/Release/net6.0/*.dll
