name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: HaymakerMod_DLL
        # これで、どこかにできた .dll を全部かき集めるぜ！
        path: "**/bin/Release/**/*.dll"
        
